""" Custom exceptions that could be generated by the program"""


class NotCorrectMessage(Exception):
    """ a message that cannot be parsed"""
    pass


class NotCorrectTaskID(Exception):
    """ not correct task id"""
    pass
